config/routes.rb
Rails.application.routes.draw do
  resources :enquiries
  resources :enquiries
  resources :attractions
  
  get "availability", :controller => "enquiries", :action => "new"
  get "pages/show_blogfeed", :controller => "pages", :action => "show_blogfeed"
  
  resources :pages
  

  get "/sitemap", :controller => 'sitemap', :action => "index"

  get ":id", :controller => "pages", :action => "show"
  
  get "/d/fr/index" => redirect("/fr/")
  get "/d/de/index" => redirect("/de/")
  get "/d/nl/index" => redirect("/nl/")
  get "/a/availability" => redirect("/availability")
  get "/d/bodiamCastle"  => redirect("/attractions/Bodiam_Castle")
  get "/d/bodiamcastle"  => redirect("/attractions/Bodiam_Castle")
  get "/d/merriments.html" => redirect("/attractions/Merriments_Gardens_and_Nursery")
  get "/places" => redirect("/attractions")
  get "/d/scotney" => redirect("/attractions/Scotney_Castle_Garden")
  get "/d/sheffieldParkGardens" => redirect("/attractions/Sheffield_Park_Garden")
  get "/d/sissinghurst" => redirect("/attractions/Sissinghurst_Castle")
  get "/d/places/BedgeburyPinetum" => redirect("/attractions/Bedgebury_Pinetum")
  get "/d/places/GreatCompGarden" => redirect("/attractions/Great_Comp_Garden")
  get "/d/places/PashleyManorGardens" => redirect("/attractions/Pashley_Manor_Gardens")
  get "/d/places/GreatDixter" => redirect("/attractions/Great_Dixter")
  get "/d/:id" => redirect("/%{id}")
  
  root :to => 'pages#show', :id => 'index' 

  
end

app/views/pages/_form.html.erb
<%= form_for(@page) do |f| %>
  <% if @page.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@page.errors.count, "error") %> prohibited this page from being saved:</h2>

      <ul>
      <% @page.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :keywords %><br />
    <%= f.text_area :keywords %>
  </div>
  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_area :content %>
  </div>
  <div class="field">
    <%= f.label :sub_content %><br />
    <%= f.text_area :sub_content %>
  </div>
  <div class="field">
    <%= f.label :parent_id %><br />
    <%= f.number_field :parent_id %>
  </div>
  <div class="field">
    <%= f.label :position %><br />
    <%= f.number_field :position %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/pages/edit.html.erb
<h1>Editing page</h1>

<%= render 'form' %>

<%= link_to 'Show', @page %> |
<%= link_to 'Back', pages_path %>

app/views/pages/index.html.erb
<h1>Listing pages</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Title</th>
    <th>Keywords</th>
    <th>Content</th>
    <th>Sub content</th>
    <th>Parent</th>
    <th>Position</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @pages.each do |page| %>
  <tr>
    <td><%= page.name %></td>
    <td><%= page.title %></td>
    <td><%= page.keywords %></td>
    <td><%= page.content %></td>
    <td><%= page.sub_content %></td>
    <td><%= page.parent_id %></td>
    <td><%= page.position %></td>
    <td><%= link_to 'Show', page %></td>
    <td><%= link_to 'Edit', edit_page_path(page) %></td>
    <td><%= link_to 'Destroy', page, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Page', new_page_path %>

app/views/pages/new.html.erb
<h1>New page</h1>

<%= render 'form' %>

<%= link_to 'Back', pages_path %>

app/views/pages/show.html.erb
<div class="container">
	<div class="row">
		<div class="col-md-8 maincontent">
			<p id="notice"><%= notice %></p>
			<%= markdown(@page.content) %>


		</div><!-- md8 -->
        <div class="col-md-4 sidebar">
			<%= markdown(@page.sub_content) %>
		</div>
	</div><!-- row -->
	<% if @page.name == "index"%>

	<div class="row">
		<div class="col-md-12 maincontent">
			<div id="blog" class="img-responsive">
			<script language="JavaScript">
			$.ajax({
			url: "<%= pages_show_blogfeed_path() %>",
			format: "html",
			cache: false,
			success: function(html){
				$("#blog").append(html);
			}
			}); 
			</script>
			</div>
		</div>
	</div>
	<% end %>
</div>

app/views/pages/show_blogfeed.html.erb
<h1>Latest News</h1>
<% @feed_entries.each do |feed_entry|  %>
  <div id="<%= feed_entry.guid %>" class="blog post class-post">
  	<h2 class="">
  	  <a href="<%= feed_entry.url %>"><%= feed_entry.published_at.strftime("%d %B") %>: <%= feed_entry.name.html_safe %></a>	
  	</h2>  
	<div class="storycontent">
		<% display_html = feed_entry.content.gsub(/img\ class\=\"/, "img class=\"img-fluid ") %>
		<% display_html = display_html.gsub(/aligncenter|size-full|wp-image-\d+/, "") %>
		<% display_html = display_html.gsub(/width\:\ \d+px/, "") %>
    	<%= raw(display_html) %>
    </div>
  </div>
<% end %>

app/views/pages/show_blogfeed.js.erb
$('#blog').html("<% @feed_entries.each do |feed_entry| 
  raw(feed_entry.content)
end %>");