config/routes.rb
Rails.application.routes.draw do
  resources :enquiries
  resources :enquiries
  resources :attractions
  
  get "availability", :controller => "enquiries", :action => "new"
  get "pages/show_blogfeed", :controller => "pages", :action => "show_blogfeed"
  
  resources :pages
  

  get "/sitemap", :controller => 'sitemap', :action => "index"

  get ":id", :controller => "pages", :action => "show"
  
  get "/d/fr/index" => redirect("/fr/")
  get "/d/de/index" => redirect("/de/")
  get "/d/nl/index" => redirect("/nl/")
  get "/a/availability" => redirect("/availability")
  get "/d/bodiamCastle"  => redirect("/attractions/Bodiam_Castle")
  get "/d/bodiamcastle"  => redirect("/attractions/Bodiam_Castle")
  get "/d/merriments.html" => redirect("/attractions/Merriments_Gardens_and_Nursery")
  get "/places" => redirect("/attractions")
  get "/d/scotney" => redirect("/attractions/Scotney_Castle_Garden")
  get "/d/sheffieldParkGardens" => redirect("/attractions/Sheffield_Park_Garden")
  get "/d/sissinghurst" => redirect("/attractions/Sissinghurst_Castle")
  get "/d/places/BedgeburyPinetum" => redirect("/attractions/Bedgebury_Pinetum")
  get "/d/places/GreatCompGarden" => redirect("/attractions/Great_Comp_Garden")
  get "/d/places/PashleyManorGardens" => redirect("/attractions/Pashley_Manor_Gardens")
  get "/d/places/GreatDixter" => redirect("/attractions/Great_Dixter")
  get "/d/:id" => redirect("/%{id}")
  
  root :to => 'pages#show', :id => 'index' 

  
end

app/models/enquiry.rb
class Enquiry < ActiveRecord::Base
  validate :some_contact_details
  validate :some_name_fields
  
  def some_contact_details
    if self.phone == "" && self.email == ""
      errors.add(:phone, "Please Supply a Phone Number or E-mail address") 
    end
  end

  def some_name_fields
    if self.firstname == "" && self.surname == ""
      errors.add(:firstname, "Please Supply a Phone Number or E-mail address") 
    end
  end
  
  
  def IsCommentSpam()
    # Original PHP code
    # $bannedlist = array("phentermine", "xenical", "paxil", "xanax", "meridia","<a href", "drug", "diazepam", "casino", "pussy", "fuck", "lesbian", "Hello, nice site look this", "Erotic", "anal", "tit", "http\:\/\/", "Hydrocodone", "prescription", "Good site, admin."  );
    #foreach ($bannedlist as $word) {
    #if ( preg_match("/.*$word.*/",  $_REQUEST['comments'] ) ) {
    #  $notspam = 0;
    #}
    #}
    
    banned_words = ["phentermine", "xenical", "paxil", "xanax", "meridia","<a href", "drug", "diazepam", "casino", "pussy", "fuck", "lesbian", "Hello, nice site look this", "Erotic", "anal", "tit", "http\:\/\/", "Hydrocodone", "prescription", "Good site, admin.", "Levitra", "cialis", "relafen" ]
    r =  banned_words.join('|') 
    regexp = Regexp.new(r, Regexp::IGNORECASE | Regexp::MULTILINE)
    score =  self.comment.scan(regexp).size

	non_letter_number = self.phone.gsub(/\D/, '')
	if self.phone.length > 0 and non_letter_number.length < 5
		score = score + 2
	end

	if self.phone == "123456"
		score = score + 3
	end

	if self.night_count < 1
		score = score + 2
	end

	if self.arrival_date < DateTime.now
		score = score + 2
	end

    return score
  
  end
end

app/controllers/enquiries_controller.rb
class EnquiriesController < ApplicationController
  # GET /enquiries
  # GET /enquiries.json
  #def index
  #  @enquiries = Enquiry.all

  #  respond_to do |format|
  #    format.html # index.html.erb
  #    format.json { render json: @enquiries }
  #  end
  #end

  # GET /enquiries/1
  # GET /enquiries/1.json
  #def show
  #  @enquiry = Enquiry.find(params[:id])

  #  respond_to do |format|
  #    format.html # show.html.erb
  #    format.json { render json: @enquiry }
  #  end
  #end

  # GET /enquiries/new
  # GET /enquiries/new.json
  def new
    @enquiry = Enquiry.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @enquiry }
    end
  end

  # GET /enquiries/1/edit
  #def edit
  #  @enquiry = Enquiry.find(params[:id])
  #end

  # POST /enquiries
  # POST /enquiries.json
  def create
  	params.fetch(:blog, {}).permit(:title, :author)
    @enquiry = Enquiry.create(params.fetch(:enquiry, {}).permit(:firstname, :surname, :phone, :email, :arrival_date, :night_count, :people, :rooms, :comment))
    
    logger.info "New enquiry: #{@enquiry.attributes.inspect}"


    respond_to do |format|
      if @enquiry.save 
        
        # Send request to Bull Farm Oast, but only if we return min of 5 links/
        # watch words
        if @enquiry.IsCommentSpam < 5
            AccomodationEnquiry.enquiry(@enquiry).deliver
        
            # Only send reply if we've not tagged this as spam at all
            unless @enquiry.IsCommentSpam 
              AccomodationEnquiry.acknowledge(@enquiry).deliver
            end
        else 
        	  logger.info "Ignoring Spam Score: #{@enquiry.IsCommentSpam}"
        end
        
        #redirect_to @enquiry, notice: 'Enquiry successfully submitted.', action: "success" 
        #format.json { render json: @enquiry, status: :created, location: @enquiry }
        format.html { render notice: 'Enquiry successfully submitted.', action: "success" }
        
      else
        render action: "new" 
        #format.json { render json: @enquiry.errors, status: :unprocessable_entity }
      end
    end
  end

  private
	def enquiry_params
		params.require(:enquiry).permit(:firstname, :surname, :phone, :email, :arrival_date, :night_count, :people, :rooms, :comment)
	end

  # PUT /enquiries/1
  # PUT /enquiries/1.json
  #def update
  #  @enquiry = Enquiry.find(params[:id])

  #  respond_to do |format|
  #    if @enquiry.update_attributes(params[:enquiry])
  #      format.html { redirect_to @enquiry, notice: 'Enquiry was successfully updated.' }
  #      format.json { head :ok }
  #    else
  #      format.html { render action: "edit" }
  #      format.json { render json: @enquiry.errors, status: :unprocessable_entity }
  #    end
  #  end
  #end

  # DELETE /enquiries/1
  # DELETE /enquiries/1.json
  #def destroy
  #  @enquiry = Enquiry.find(params[:id])
  #  @enquiry.destroy

  #  respond_to do |format|
  #    format.html { redirect_to enquiries_url }
  #    format.json { head :ok }
  #  end
  #end
end

app/helpers/enquiries_helper.rb
module EnquiriesHelper
end

app/views/enquiries/_form.html.erb
<%= form_for(@enquiry) do |f| %>
  <% if @enquiry.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@enquiry.errors.count, "error") %> prohibited this enquiry from being saved:</h2>

      <ul>
      <% @enquiry.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

 
  <div class="form-group row">
	  <%= f.label :firstname, :class=>"col-sm-2 col-form-label" %>
	  <div class="col-sm-6">
		  <%= f.text_field :firstname, :class=>"form-control" %>
	   </div>
  </div>
  <div class="form-group row">
    <%= f.label :surname , :class=>"col-sm-2 col-form-label"%>
	  <div class="col-sm-6">
    <%= f.text_field :surname , :class=>"form-control"%>
	   </div>
  </div>
  <div class="form-group row">
    <%= f.label :phone , :class=>"col-sm-2 col-form-label"%>
	  <div class="col-sm-6">
    <%= f.text_field :phone, :class=>"form-control" %>
	   </div>
  </div>
  <div class="form-group row">
    <%= f.label :email , :class=>"col-sm-2 col-form-label"%>
	  <div class="col-sm-6">
    <%= f.text_field :email, :class=>"form-control" %>
	   </div>
  </div>
  <div class="form-group row">
    <%= f.label :arrival_date , :class=>"col-sm-2 col-form-label"%>
	<div class="col-sm-6">
		<%= f.date_field :arrival_date, :class=>"form-control", :min=>"01-01-2017" %>
	   </div>
  </div>
  <div class="form-group row">
    <%= f.label :night_count , :class=>"col-sm-2 col-form-label"%>
	  <div class="col-sm-6">
         <%= f.number_field :night_count, :class=>"form-control" %>
	  </div>
  </div>
  <div class="form-group row">
    <%= f.label :people , :class=>"col-sm-2 col-form-label"%>
	  <div class="col-sm-6">
		  <%= select(:enquiry, :people, options_for_select([['1 Person', 1], ['2 People', 2], ['3 People', 3], ['4 People', 4], ['5 People', 5], ['6 People', 6]], 2), {}, {:class=>"form-control"}) %>
	  </div>
  </div>
  <div class="form-group row">
    <%= f.label :rooms , :class=>"col-sm-2 col-form-label"%>
	  <div class="col-sm-6">
		  <%= select(:enquiry, :rooms, options_for_select([['1 Room', 1], ['2 Rooms', 2]], 1), {}, {:class=>"form-control"}) %>
	   </div>
  </div>
  <div class="form-group row">
    <%= f.label :comment , :class=>"col-sm-2 col-form-label"%>
	  <div class="col-sm-6">
		  <%= f.text_area :comment, :class=>"form-control", rows: 7 %>
	   </div>
  </div>
  <div class="form-group row">
	  <div class="offset-sm-2 col-sm-10">
	  <%= f.submit 'Make Enquiry', :class => "btn btn-primary" %>
	   </div>
   </div>
</div>
<% end %>

app/views/enquiries/edit.html.erb
<h1>Editing enquiry</h1>

<%= render 'form' %>

<%= link_to 'Show', @enquiry %> |
<%= link_to 'Back', enquiries_path %>

app/views/enquiries/index.html.erb
<h1>Listing enquiries</h1>

<table>
  <tr>
    <th>Firstname</th>
    <th>Surname</th>
    <th>Phone</th>
    <th>Email</th>
    <th>Arrival date</th>
    <th>Night count</th>
    <th>People</th>
    <th>Rooms</th>
    <th>Comment</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @enquiries.each do |enquiry| %>
  <tr>
    <td><%= enquiry.firstname %></td>
    <td><%= enquiry.surname %></td>
    <td><%= enquiry.phone %></td>
    <td><%= enquiry.email %></td>
    <td><%= enquiry.arrival_date %></td>
    <td><%= enquiry.night_count %></td>
    <td><%= enquiry.people %></td>
    <td><%= enquiry.rooms %></td>
    <td><%= enquiry.comment %></td>
    <td><%= link_to 'Show', enquiry %></td>
    <td><%= link_to 'Edit', edit_enquiry_path(enquiry) %></td>
    <td><%= link_to 'Destroy', enquiry, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Enquiry', new_enquiry_path %>

app/views/enquiries/new.html.erb
<div class="container">
  <p id="notice"><%= notice %></p>
  	
  	<p>
  		Enter details of when you are planning to arrive and how long you would like to stay, we will get back to you within a day to confirm your booking.
    </p>
	<%= render 'form' %>
</div>
  

app/views/enquiries/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Firstname:</b>
  <%= @enquiry.firstname %>
</p>

<p>
  <b>Surname:</b>
  <%= @enquiry.surname %>
</p>

<p>
  <b>Phone:</b>
  <%= @enquiry.phone %>
</p>

<p>
  <b>Email:</b>
  <%= @enquiry.email %>
</p>

<p>
  <b>Arrival date:</b>
  <%= @enquiry.arrival_date %>
</p>

<p>
  <b>Night count:</b>
  <%= @enquiry.night_count %>
</p>

<p>
  <b>People:</b>
  <%= @enquiry.people %>
</p>

<p>
  <b>Rooms:</b>
  <%= @enquiry.rooms %>
</p>

<p>
  <b>Comment:</b>
  <%= @enquiry.comment %>
</p>


<%= link_to 'Edit', edit_enquiry_path(@enquiry) %> |
<%= link_to 'Back', enquiries_path %>

app/views/enquiries/success.html.erb
<div class="container">
	<p id="notice"><%= notice %></p>

	<h1>Request Recieved</h1>

	<p>Thank you for your request for <%= pluralize(@enquiry.night_count, 'night') %> accomodation, from the
	<%= @enquiry.arrival_date %> for <%= pluralize(@enquiry.people, 'person') %> staying in <%= pluralize(@enquiry.rooms, 'room') %>. We reply to you at
	<%= @enquiry.email %> within one day. If you require further information in advance then please
	call us on 01580 714 140 or email us at <a href="mailto:b+b@bullfarmoast.co.uk">b+b@bullfarmoast.co.uk</a>.
	</p>
	<p>We have also sent you a confirmation of this request to <%= @enquiry.email %></p>
</div> 